services:
  api:
    build: 
      context: ./data-analysis
    ports:
      - "8000:8000"
    volumes:
      - ./data-analysis:/app
      - sensor_data:/app/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=gemma3:4b
      - OLLAMA_TIMEOUT=500
      - SENSOR_API_URL=http://host.docker.internal:8080/datos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    restart: unless-stopped
    # deploy:
     # resources:
       # reservations:
       #   devices:
           # - driver: nvidia
           #   count: 1
           #   capabilities: [gpu]

volumes:
  ollama_data:
  sensor_data: 