services:
  api:
    build: 
      context: ./data-analysis
    ports:
      - "8000:8000"
    volumes:
      - ./data-analysis:/app
      - sensor_data:/app/data
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=gemma3:4b
      - SENSOR_API_URL=http://host.docker.internal:8080/datos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  sensor_data: 